services:
  control-plane:
    build: ./control-plane-service
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      CASSANDRA_CONTACT_POINTS: cassandra
      CASSANDRA_LOCAL_DATACENTER: datacenter1
    depends_on:
      - redis
      - cassandra

  redis:
    image: valkey/valkey:7.2
    ports:
      - "6379:6379"

  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: gfn-control-plane
      CASSANDRA_DC: datacenter1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch

